
package orderSystem.client;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebService(name = "ProcessOrderImpl", targetNamespace = "jaxws.orderSystem/orderprocess")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface ProcessOrderImpl {


    /**
     * 
     * @param arg0
     * @return
     *     returns orderSystem.client.OrderBean
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "orderPorcessing", targetNamespace = "jaxws.orderSystem/orderprocess", className = "orderSystem.client.OrderPorcessing")
    @ResponseWrapper(localName = "orderPorcessingResponse", targetNamespace = "jaxws.orderSystem/orderprocess", className = "orderSystem.client.OrderPorcessingResponse")
    public OrderBean orderPorcessing(
        @WebParam(name = "arg0", targetNamespace = "")
        OrderBean arg0);

}
